### ISSUE TITLE
ImportError with 'mrimotion' module in multicoil_motion_simulator.py

### ISSUE THREAD

**Issue by mojiexiaozi** [nalinimsingh/neuroMoCo#1]
I encountered an ImportError while trying to run multicoil_motion_simulator.py. It seems the script is unable to locate the 'mrimotion' module.
I appreciate any assistance in resolving this issue. Thank you!

**Comment by nalinimsingh** [comment]
So sorry for the late response -- I missed the notification for this. 

Unfortunately, the mrimotion module cannot be released, as it references proprietary information specific to our image acquisition. Each user will need to write their own version of multicoil_motion_simulator.py based on their specific MR acquisition -- let me know if you need any help with this.

**Comment by nalinimsingh** [comment]
Marking as closed, feel free to reopen or let me know if I can help in anyway.

**Comment by mojiexiaozi** [comment]
oh, thanks for your response.
