### ISSUE TITLE
Is 'import mrimotion as mot' a separate python package or its a separate repository/project?

### ISSUE THREAD

**Issue by gulfam7** [nalinimsingh/neuroMoCo#2]
From the multicoil_motion_simulator.py,  there's a 'import mrimotion as mot'. Is 'mrimotion' a python package? There's no installation for this in 'environment.yml'. Moreover, there's no mention of it anywhere else, whether it's a repo or package.

**Comment by nalinimsingh** [comment]
So sorry, I missed this issue. See discussion in #1, and feel free to reopen if you have any questions or need help writing your own simulator to fit the rest of the codebase.
